import '../models/food_item.dart';

class MockData {
  static const List<String> categories = ['All', 'Combos', 'Pizza', 'Burger', 'Drinks'];

  static final List<FoodItem> foodItems = [
    // Burgers
    FoodItem(
      id: '1',
      name: 'Classic Cheeseburger',
      subtitle: 'Flame Grilled Beef',
      price: 5.99,
      rating: 4.8,
      imageUrl: 'assets/images/burger.png',
      category: 'Burger',
    ),
    FoodItem(
      id: '2',
      name: 'Bacon Whopper',
      subtitle: 'Crispy Bacon & Cheddar',
      price: 6.80,
      rating: 4.9,
      imageUrl: 'assets/images/burger2.png',
      category: 'Burger',
    ),
    FoodItem(
      id: '3',
      name: 'Mushroom Swiss Burger',
      subtitle: 'Sautéed Mushrooms',
      price: 6.25,
      rating: 4.6,
      imageUrl: 'assets/images/burger3.png',
      category: 'Burger',
    ),
    FoodItem(
      id: '4',
      name: 'Spicy Zinger Burger',
      subtitle: 'Crispy Fried Chicken',
      price: 5.50,
      rating: 4.7,
      imageUrl: 'assets/images/burger4.png',
      category: 'Burger',
    ),
    FoodItem(
      id: '5',
      name: 'Double Smash Burger',
      subtitle: 'Caramelized Onions',
      price: 7.50,
      rating: 4.9,
      imageUrl: 'assets/images/burger5.png',
      category: 'Burger',
    ),

    // Pizza
    FoodItem(
      id: '6',
      name: 'Pepperoni Supreme',
      subtitle: 'Mozzarella & Oregano',
      price: 11.99,
      rating: 4.9,
      imageUrl: 'assets/images/pizza.png',
      category: 'Pizza',
    ),
    FoodItem(
      id: '7',
      name: 'Margherita Delight',
      subtitle: 'Fresh Basil & Tomato',
      price: 9.50,
      rating: 4.5,
      imageUrl: 'assets/images/pizza2.jpg',
      category: 'Pizza',
    ),
    FoodItem(
      id: '8',
      name: 'BBQ Chicken Pizza',
      subtitle: 'Smoky BBQ & Red Onion',
      price: 12.50,
      rating: 4.8,
      imageUrl: 'assets/images/pizza3.jpg',
      category: 'Pizza',
    ),
    FoodItem(
      id: '9',
      name: 'Four Cheese Feast',
      subtitle: 'Parmesan, Cheddar, Mozz',
      price: 10.99,
      rating: 4.7,
      imageUrl: 'assets/images/pizza4.jpg',
      category: 'Pizza',
    ),
    FoodItem(
      id: '10',
      name: 'Hawaiian Special',
      subtitle: 'Ham & Sweet Pineapple',
      price: 10.50,
      rating: 4.3,
      imageUrl: 'assets/images/pizza5.jpg',
      category: 'Pizza',
    ),

    // Combos
    FoodItem(
      id: '11',
      name: 'Family Feast Combo',
      subtitle: '2 Burgers, 2 Drinks, Fries',
      price: 18.99,
      rating: 4.9,
      imageUrl: 'assets/images/combo1.jpg',
      category: 'Combos',
    ),
    FoodItem(
      id: '12',
      name: 'Solo Meal Deal',
      subtitle: '1 Burger, Fries & Soda',
      price: 8.99,
      rating: 4.7,
      imageUrl: 'assets/images/combo2.jpg',
      category: 'Combos',
    ),
    FoodItem(
      id: '13',
      name: 'Pizza & Wings Combo',
      subtitle: 'Medium Pizza + 6 Wings',
      price: 16.50,
      rating: 4.8,
      imageUrl: 'assets/images/combo3.jpg',
      category: 'Combos',
    ),
    FoodItem(
      id: '14',
      name: 'Double Trouble Pack',
      subtitle: '2 Smash Burgers & Shake',
      price: 14.20,
      rating: 4.6,
      imageUrl: 'assets/images/combo4.jpg',
      category: 'Combos',
    ),

    // Drinks
    FoodItem(
      id: '15',
      name: 'Iced Vanilla Latte',
      subtitle: 'Cold Brewed Coffee',
      price: 3.50,
      rating: 4.6,
      imageUrl: 'assets/images/drink1.jpg',
      category: 'Drinks',
    ),
    FoodItem(
      id: '16',
      name: 'Fresh Mango Smoothie',
      subtitle: '100% Real Fruit',
      price: 4.25,
      rating: 4.8,
      imageUrl: 'assets/images/drink2.jpg',
      category: 'Drinks',
    ),
    FoodItem(
      id: '17',
      name: 'Chocolate Milkshake',
      subtitle: 'Rich Creamy Fudge',
      price: 4.50,
      rating: 4.9,
      imageUrl: 'assets/images/drink3.jpg',
      category: 'Drinks',
    ),
    FoodItem(
      id: '18',
      name: 'Classic Lemonade',
      subtitle: 'Freshly Squeezed',
      price: 2.99,
      rating: 4.4,
      imageUrl: 'assets/images/drink4.jpg',
      category: 'Drinks',
    ),
  ];
}